import caffe
import sys
import os
import skimage

import full_image_classify as minc_utils
import classify_resized as resize
from scipy import misc
import numpy as np
from datetime import datetime

SCALES = [1.0/np.sqrt(2), 1.0, np.sqrt(2)]  # Define scales as per MINC paper

def upscale(im_path):
    """
    Function for performing upscaling of probability maps generated by MINC model
    :return:
    """

    im_files = resize.resize_image(im_path)  # perform image resizing
    outputs = [minc_utils.classify(image) for image in im_files]  # Perform classification on images
    prob_maps = [minc_utils.get_probability_maps(out) for out in outputs]  # Get probability maps for each class for each image
    

if __name__ == "__main__":
    caffe.set_mode_gpu()
    image_path = sys.argv[1]  # path to image to be segmented
    upscale(image_path)

